# Generated by Django 5.2.10 on 2026-01-25 07:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chalet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="أدخل اسم الشاليه",
                        max_length=200,
                        verbose_name="اسم الشاليه",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="أدخل وصفاً تفصيلياً للشاليه",
                        verbose_name="وصف الشاليه",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="وصف مختصر يظهر في الصفحة الرئيسية",
                        max_length=300,
                        verbose_name="وصف مختصر",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="عنوان أو موقع الشاليه",
                        max_length=300,
                        verbose_name="الموقع",
                    ),
                ),
                (
                    "location_url",
                    models.URLField(
                        blank=True,
                        help_text="رابط Google Maps أو أي خريطة أخرى",
                        null=True,
                        verbose_name="رابط الموقع على الخريطة",
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="السعر بالدينار العراقي",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="سعر الليلة",
                    ),
                ),
                (
                    "max_guests",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="الحد الأقصى لعدد النزلاء",
                        verbose_name="أقصى عدد نزلاء",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="هل الشاليه متاح للحجز؟",
                        verbose_name="نشط",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "شاليه",
                "verbose_name_plural": "الشاليهات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="رقم الهاتف"
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="الموضوع")),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="تمت القراءة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإرسال"
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة اتصال",
                "verbose_name_plural": "رسائل الاتصال",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="أدخل اسمك الكامل",
                        max_length=100,
                        verbose_name="الاسم الكامل",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="أدخل بريدك الإلكتروني",
                        max_length=254,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="أدخل رقم هاتفك. مثال: 07701234567",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="أدخل رقم هاتف عراقي صحيح. مثال: 07701234567",
                                regex="^(\\+964|0)?7[0-9]{9}$",
                            )
                        ],
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "check_in",
                    models.DateField(
                        help_text="تاريخ بداية الإقامة", verbose_name="تاريخ الوصول"
                    ),
                ),
                (
                    "check_out",
                    models.DateField(
                        help_text="تاريخ نهاية الإقامة", verbose_name="تاريخ المغادرة"
                    ),
                ),
                (
                    "guests",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="عدد الأشخاص",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="عدد النزلاء",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="أي ملاحظات أو طلبات خاصة",
                        verbose_name="ملاحظات",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "جديد - قيد المراجعة"),
                            ("confirmed", "مؤكد"),
                            ("cancelled", "ملغى"),
                            ("completed", "مكتمل"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="حالة الحجز",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="السعر الإجمالي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الحجز"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "chalet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="chalet.chalet",
                        verbose_name="الشاليه",
                    ),
                ),
            ],
            options={
                "verbose_name": "حجز",
                "verbose_name_plural": "الحجوزات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChaletFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="مثال: بركة سباحة، واي فاي",
                        max_length=100,
                        verbose_name="اسم الميزة",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("fa-swimming-pool", "بركة سباحة"),
                            ("fa-wifi", "واي فاي"),
                            ("fa-utensils", "مطبخ"),
                            ("fa-snowflake", "تكييف"),
                            ("fa-tv", "تلفزيون"),
                            ("fa-parking", "موقف سيارات"),
                            ("fa-bed", "غرف نوم"),
                            ("fa-bath", "حمامات"),
                            ("fa-tree", "حديقة"),
                            ("fa-fire", "شواء/باربكيو"),
                            ("fa-gamepad", "ألعاب"),
                            ("fa-child", "ألعاب أطفال"),
                            ("fa-shield-alt", "أمن وحراسة"),
                            ("fa-concierge-bell", "خدمة الغرف"),
                            ("fa-hot-tub", "جاكوزي"),
                            ("fa-umbrella-beach", "مظلات"),
                            ("fa-couch", "غرفة معيشة"),
                            ("fa-blender", "أجهزة مطبخ"),
                            ("fa-door-open", "مدخل خاص"),
                            ("fa-users", "مجالس"),
                        ],
                        default="fa-check",
                        help_text="اختر أيقونة مناسبة للميزة",
                        max_length=50,
                        verbose_name="الأيقونة",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="وصف إضافي للميزة (اختياري)",
                        max_length=200,
                        verbose_name="وصف الميزة",
                    ),
                ),
                (
                    "chalet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="chalet.chalet",
                        verbose_name="الشاليه",
                    ),
                ),
            ],
            options={
                "verbose_name": "ميزة الشاليه",
                "verbose_name_plural": "مزايا الشاليه",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChaletImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="chalet_images/", verbose_name="الصورة"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="وصف مختصر للصورة",
                        max_length=200,
                        verbose_name="وصف الصورة",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="هل هذه الصورة الرئيسية للشاليه؟",
                        verbose_name="صورة رئيسية",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="ترتيب ظهور الصورة", verbose_name="الترتيب"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                (
                    "chalet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="chalet.chalet",
                        verbose_name="الشاليه",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة الشاليه",
                "verbose_name_plural": "صور الشاليه",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
