# Generated by Django 5.2.10 on 2026-01-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chalet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chalet",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="رفع فيديو تعريفي للشاليه (MP4, WebM, Ogg)",
                null=True,
                upload_to="chalet_videos/",
                verbose_name="فيديو تعريفي",
            ),
        ),
    ]
