# Generated by Django 5.2.10 on 2026-01-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chalet", "0002_chalet_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="chalet",
            name="youtube_video",
            field=models.URLField(
                blank=True,
                help_text="أدخل رابط فيديو يوتيوب (مثال: https://www.youtube.com/watch?v=...)",
                null=True,
                verbose_name="رابط فيديو يوتيوب",
            ),
        ),
    ]
