# Generated by Django 5.2.10 on 2026-01-25 13:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chalet", "0003_chalet_youtube_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="اسم العميل"),
                ),
                (
                    "customer_image",
                    models.ImageField(
                        blank=True,
                        help_text="صورة العميل (اختياري)",
                        null=True,
                        upload_to="customer_reviews/",
                        verbose_name="صورة العميل",
                    ),
                ),
                ("comment", models.TextField(verbose_name="التعليق")),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="من 1 إلى 5 نجوم",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="التقييم",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="عرض هذا الرأي في الموقع",
                        verbose_name="نشط",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                (
                    "chalet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="chalet.chalet",
                        verbose_name="الشاليه",
                    ),
                ),
            ],
            options={
                "verbose_name": "رأي عميل",
                "verbose_name_plural": "آراء العملاء",
                "ordering": ["-created_at"],
            },
        ),
    ]
