# Generated by Django 4.2.7 on 2026-06-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chalet", "0004_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="شاليه النرجس",
                        max_length=100,
                        verbose_name="اسم الموقع",
                    ),
                ),
                (
                    "site_description",
                    models.TextField(
                        default="أفضل شاليه للإيجار اليومي والأسبوعي",
                        verbose_name="وصف الموقع",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        default="+964 770 000 0000",
                        max_length=20,
                        verbose_name="رقم الهاتف الأساسي",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        default="+9647700000000",
                        help_text="بدون فواصل، استخدم رمز الدولة مثل +964",
                        max_length=20,
                        verbose_name="رقم الواتساب",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        default="info@narjis-chalet.com",
                        max_length=254,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "location_text",
                    models.CharField(
                        default="العراق",
                        max_length=200,
                        verbose_name="نص الموقع (العنوان)",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, null=True, verbose_name="رابط فيسبوك"),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="رابط انستغرام"
                    ),
                ),
                (
                    "telegram_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="رابط تيليجرام"
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#557baf",
                        help_text="مثال: #557baf",
                        max_length=7,
                        verbose_name="اللون الأساسي (Primary Color)",
                    ),
                ),
                (
                    "primary_dark_color",
                    models.CharField(
                        default="#2862b9",
                        help_text="مثال: #2862b9",
                        max_length=7,
                        verbose_name="اللون الداكن (Primary Dark)",
                    ),
                ),
                (
                    "primary_light_color",
                    models.CharField(
                        default="#467bbb",
                        help_text="مثال: #467bbb",
                        max_length=7,
                        verbose_name="اللون الفاتح (Primary Light)",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#c5a059",
                        help_text="مثال: #c5a059",
                        max_length=7,
                        verbose_name="اللون الثانوي/الذهبي (Secondary Color)",
                    ),
                ),
                (
                    "secondary_dark_color",
                    models.CharField(
                        default="#a07d3b",
                        help_text="مثال: #a07d3b",
                        max_length=7,
                        verbose_name="اللون الثانوي الداكن (Secondary Dark)",
                    ),
                ),
                (
                    "secondary_light_color",
                    models.CharField(
                        default="#e5c482",
                        help_text="مثال: #e5c482",
                        max_length=7,
                        verbose_name="اللون الثانوي الفاتح (Secondary Light)",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات الموقع",
                "verbose_name_plural": "إعدادات الموقع",
            },
        ),
    ]
