# Generated by Django 4.2.7 on 2026-06-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chalet", "0005_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_time",
            field=models.CharField(
                choices=[
                    ("morning", "صباحي"),
                    ("evening", "مسائي"),
                    ("night", "ليلي"),
                    ("full_day", "يوم كامل"),
                ],
                default="full_day",
                help_text="اختر وقت الحجز المناسب",
                max_length=20,
                verbose_name="وقت الحجز",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="أدخل بريدك الإلكتروني (اختياري)",
                max_length=254,
                null=True,
                verbose_name="البريد الإلكتروني",
            ),
        ),
    ]
