# Generated by Django 4.2.7 on 2026-06-11 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chalet", "0006_booking_booking_time_alter_booking_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="booking_time",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="check_out",
        ),
        migrations.RemoveField(
            model_name="chalet",
            name="price_per_night",
        ),
        migrations.AddField(
            model_name="booking",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("عائلية", "عائلية"),
                    ("شباب", "شباب"),
                    ("عيد ميلاد", "عيد ميلاد"),
                    ("حنة", "حنة"),
                    ("سفرة مدرسية", "سفرة مدرسية"),
                    ("أخرى", "أخرى"),
                ],
                default="عائلية",
                max_length=50,
                verbose_name="نوع المناسبة",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="shift_evening",
            field=models.BooleanField(
                default=False, verbose_name="المسائي (5 م - 11 م)"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="shift_morning",
            field=models.BooleanField(
                default=False, verbose_name="الصباحي (8 ص - 3 م)"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="shift_overnight",
            field=models.BooleanField(
                default=False, verbose_name="المبيت (12 ل - 6 ص)"
            ),
        ),
        migrations.AddField(
            model_name="chalet",
            name="evening_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="السعر بالدينار العراقي لشفت (5 عصراً - 11 ليلاً)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="سعر الشفت المسائي",
            ),
        ),
        migrations.AddField(
            model_name="chalet",
            name="morning_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="السعر بالدينار العراقي لشفت (8 صباحاً - 3 ظهراً)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="سعر الشفت الصباحي",
            ),
        ),
        migrations.AddField(
            model_name="chalet",
            name="overnight_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="السعر بالدينار العراقي لشفت (12 منتصف الليل - 6 صباحاً)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="سعر شفت المبيت",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_in",
            field=models.DateField(
                help_text="تاريخ الإقامة", verbose_name="تاريخ الحجز"
            ),
        ),
    ]
