# Generated by Django 4.2.7 on 2026-06-12 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chalet",
            "0007_remove_booking_booking_time_remove_booking_check_out_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("عائلية", "عائلية"),
                    ("شباب", "شباب"),
                    ("عيد ميلاد", "عيد ميلاد"),
                    ("حنة", "حنة"),
                    ("سفرة مدرسية", "سفرة مدرسية"),
                    ("حفل تخرج", "حفل تخرج"),
                    ("أخرى", "أخرى"),
                ],
                default="عائلية",
                max_length=50,
                verbose_name="نوع المناسبة",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="phone",
            field=models.CharField(
                help_text="أدخل رقم هاتفك. مثال: 07701234567",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل رقم هاتف عراقي صحيح يتكون من 11 رقماً ويبدأ بـ 07. مثال: 07701234567",
                        regex="^07[0-9]{9}$",
                    )
                ],
                verbose_name="رقم الهاتف",
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل رقم هاتف عراقي صحيح يتكون من 11 رقماً ويبدأ بـ 07. مثال: 07701234567",
                        regex="^07[0-9]{9}$",
                    )
                ],
                verbose_name="رقم الهاتف",
            ),
        ),
    ]
