# Generated by Django 4.2.7 on 2026-06-16 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chalet", "0008_alter_booking_event_type_alter_booking_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="البريد الإلكتروني"
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل رقم هاتف عراقي صحيح يتكون من 11 رقماً ويبدأ بـ 07. مثال: 07701234567",
                        regex="^07[0-9]{9}$",
                    )
                ],
                verbose_name="رقم الهاتف",
            ),
        ),
    ]
