# Generated by Django 4.2.7 on 2026-06-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chalet", "0009_alter_contactmessage_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="phone_number",
            field=models.CharField(
                default="+964 778 275 5075",
                max_length=20,
                verbose_name="رقم الهاتف الأساسي",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="whatsapp_number",
            field=models.CharField(
                default="+9647782755075",
                help_text="بدون فواصل، استخدم رمز الدولة مثل +964",
                max_length=20,
                verbose_name="رقم الواتساب",
            ),
        ),
    ]
