# Generated by Django 4.2.7 on 2026-06-16 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chalet", "0010_alter_sitesettings_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create_booking", "تقديم طلب حجز"),
                            ("update_booking_status", "تحديث حالة حجز"),
                            ("create_contact_message", "إرسال رسالة اتصال"),
                            ("other", "عملية أخرى"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="نوع العملية",
                    ),
                ),
                ("description", models.TextField(verbose_name="تفاصيل العملية")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="التاريخ والوقت"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تحركات النظام",
                "verbose_name_plural": "سجل تحركات النظام",
                "ordering": ["-created_at"],
            },
        ),
    ]
