# Generated by Django 4.2.7 on 2026-06-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chalet", "0011_systemlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("create_booking", "تقديم طلب حجز"),
                    ("update_booking_status", "تحديث حالة حجز"),
                    ("delete_booking", "حذف حجز"),
                    ("create_contact_message", "إرسال رسالة اتصال"),
                    ("other", "عملية أخرى"),
                ],
                default="other",
                max_length=50,
                verbose_name="نوع العملية",
            ),
        ),
    ]
